site_name: RLBot Wiki

theme:
  name: material
  logo: assets/rlbot-logo.svg
  favicon: assets/rlbot-logo.svg
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: custom
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: custom
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/zbaAKPt
    - icon: fontawesome/brands/github
      link: https://github.com/RLBot

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
  - pymdownx.superfences 