site_name: RLBot Wiki

theme:
  name: material
  logo: assets/rlbot-logo.svg
  favicon: assets/rlbot-logo.svg
  palette:
    primary: custom

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
  - pymdownx.superfences 